// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.CompositionItemInstance = (function(superClass) {
  extend(CompositionItemInstance, superClass);

  function CompositionItemInstance(data) {
    this.ignoredProperties = ["parentFolder"];
    CompositionItemInstance.__super__.constructor.apply(this, arguments);
    this.initiate(data);
  }

  CompositionItemInstance.prototype.store = function() {
    var base;
    CompositionItemInstance.__super__.store.call(this, app.project.items.addComp(this.data.name, this.data.width, this.data.height, this.data.pixelAspect, this.data.duration, this.data.framerate));
    this.item.bgColor = new Hyle.PropertyInstance("color", this.data.color).adapt().getPropertyValue();
    return typeof (base = this.item).openInViewer === "function" ? base.openInViewer() : void 0;
  };

  CompositionItemInstance.prototype.setParentComposition = function(parentComposition) {
    return parentComposition.layers.add(this.item);
  };

  return CompositionItemInstance;

})(Hyle.CompositionItem);
