// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.CompositionItemsCollection = (function(_super) {
  __extends(CompositionItemsCollection, _super);

  function CompositionItemsCollection() {
    this.compositions = [];
  }

  CompositionItemsCollection.prototype.add = function(composition) {
    var _base;
    (_base = composition.item)._id || (_base._id = composition.item.name);
    return this.compositions[composition.item._id] = composition;
  };

  CompositionItemsCollection.prototype.find = function(key) {
    return this.compositions[key];
  };

  return CompositionItemsCollection;

})(Hyle.Collection);
