// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.CompositionItemsCollection = (function(superClass) {
  extend(CompositionItemsCollection, superClass);

  function CompositionItemsCollection() {
    this.compositions = [];
  }

  CompositionItemsCollection.prototype.add = function(composition) {
    var base;
    (base = composition.item)._id || (base._id = composition.item.name);
    return this.compositions[composition.item._id] = composition;
  };

  CompositionItemsCollection.prototype.find = function(key) {
    return this.compositions[key];
  };

  return CompositionItemsCollection;

})(Hyle.Collection);
