// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.CompositionItemsFactory = (function(_super) {
  __extends(CompositionItemsFactory, _super);

  function CompositionItemsFactory(compositionsData) {
    this.composition;
    this.compositionItemsCollection = hyle.parser.compositionItemsCollection;
    this.folderItemsCollection = hyle.parser.folderItemsCollection;
    this.createCompositions(compositionsData);
  }

  CompositionItemsFactory.prototype.createCompositions = function(compositionsData) {
    var compositionData, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = compositionsData.length; _i < _len; _i++) {
      compositionData = compositionsData[_i];
      this.composition = new Hyle.CompositionItemInstance(compositionData);
      this.composition.store();
      if (compositionData.composition) {
        this.setParentComposition(compositionData.composition);
      }
      if (compositionData.folder) {
        this.setParentFolder(compositionData.folder);
      }
      if (compositionData.fetch) {
        this.fetchComposition(compositionData.fetch);
      }
      if (compositionData.layers) {
        this.createLayers(compositionData.layers);
      }
      _results.push(this.compositionItemsCollection.add(this.composition));
    }
    return _results;
  };

  CompositionItemsFactory.prototype.setParentComposition = function(compositionPointer) {
    var parentComposition;
    parentComposition = this.compositionItemsCollection.find(compositionPointer).item;
    return this.composition.setParentComposition(parentComposition);
  };

  CompositionItemsFactory.prototype.fetchComposition = function(compositionPointer) {
    var fetchedComposition;
    fetchedComposition = this.compositionItemsCollection.find(compositionPointer).item;
    return this.composition.item.layers.add(fetchedComposition);
  };

  CompositionItemsFactory.prototype.setParentFolder = function(folderPointer) {
    var parentFolder;
    parentFolder = this.folderItemsCollection.find(folderPointer).item;
    return this.composition.setParentFolder(parentFolder);
  };

  CompositionItemsFactory.prototype.createLayers = function(layersData) {
    var layersFactory;
    return layersFactory = new Hyle.LayersFactory(layersData, this.composition);
  };

  return CompositionItemsFactory;

})(Hyle.Factory);
