// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.CompositionItemInterpretor = (function(_super) {
  __extends(CompositionItemInterpretor, _super);

  function CompositionItemInterpretor(composition) {
    this.composition = composition;
    this.ignoredProperties = [];
    this.data = {};
    this.ignoredValues = {
      parentFolder: "Root"
    };
    CompositionItemInterpretor.__super__.constructor.apply(this, arguments);
  }

  CompositionItemInterpretor.prototype.compact = function() {
    this.data = CompositionItemInterpretor.__super__.compact.call(this, this.composition);
    if (this.hasLayers()) {
      this.interpretLayers();
    }
    return this.data;
  };

  CompositionItemInterpretor.prototype.hasLayers = function() {
    if (this.composition.layers.length > 0) {
      return true;
    } else {
      return false;
    }
  };

  CompositionItemInterpretor.prototype.interpretLayers = function() {
    var i, layerInterpretor, _i, _ref, _results;
    this.data.layers = [];
    _results = [];
    for (i = _i = 1, _ref = this.composition.layers.length; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      layerInterpretor = new Hyle.LayerInterpretor(this.composition.layers[i]);
      _results.push(this.data.layers.push(layerInterpretor.compact()));
    }
    return _results;
  };

  return CompositionItemInterpretor;

})(Hyle.CompositionItem);
