// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.CompositionItem = (function(superClass) {
  extend(CompositionItem, superClass);

  function CompositionItem(data) {
    CompositionItem.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      label: 15,
      width: 1920,
      height: 1080,
      pixelAspect: 1,
      duration: 10,
      framerate: 24,
      color: [0, 0, 0]
    });
    this.initiate(data);
    this;
  }

  return CompositionItem;

})(Hyle.Item);
