// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.CompositionItem = (function(_super) {
  __extends(CompositionItem, _super);

  function CompositionItem(data) {
    CompositionItem.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      label: 15,
      width: 1920,
      height: 1080,
      pixelAspect: 1,
      duration: 10,
      framerate: 24,
      color: [0, 0, 0]
    });
    this.initiate(data);
    this;
  }

  return CompositionItem;

})(Hyle.Item);
