// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.Item = (function(superClass) {
  extend(Item, superClass);

  function Item() {
    this.defaults = {};
    this.data = {};
    this.item = {};
    this.setDefaults({
      name: null,
      parentFolder: null,
      folder: null,
      comment: "",
      selected: false
    });
  }

  Item.prototype.initiate = function(data) {
    return this.data = this.extend(data, this.defaults);
  };

  Item.prototype.setDefaults = function(defaults) {
    var key, results;
    results = [];
    for (key in defaults) {
      results.push(this.defaults[key] = defaults[key]);
    }
    return results;
  };

  Item.prototype.store = function(item) {
    this.item = item;
    this.data = this.adaptObject(this.data);
    return this.apply(this.item, this.data);
  };

  Item.prototype.setParentFolder = function(parentFolder) {
    return this.item.parentFolder = parentFolder;
  };

  return Item;

})(Hyle.Object);
