// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.Item = (function(_super) {
  __extends(Item, _super);

  function Item() {
    this.defaults = {};
    this.data = {};
    this.item = {};
    this.setDefaults({
      name: null,
      parentFolder: null,
      folder: null,
      comment: "",
      selected: false
    });
  }

  Item.prototype.initiate = function(data) {
    return this.data = this.extend(data, this.defaults);
  };

  Item.prototype.setDefaults = function(defaults) {
    var key, _results;
    _results = [];
    for (key in defaults) {
      _results.push(this.defaults[key] = defaults[key]);
    }
    return _results;
  };

  Item.prototype.store = function(item) {
    this.item = item;
    this.data = this.adaptObject(this.data);
    return this.apply(this.item, this.data);
  };

  Item.prototype.setParentFolder = function(parentFolder) {
    return this.item.parentFolder = parentFolder;
  };

  return Item;

})(Hyle.Object);
