// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.PropertyGroup = (function(_super) {
  __extends(PropertyGroup, _super);

  function PropertyGroup(data) {
    this.data = data;
  }

  PropertyGroup.prototype.applyTo = function(object) {
    return this.apply(object, this.data);
  };

  return PropertyGroup;

})(Hyle.Object);
