// Generated by CoffeeScript 1.10.0
Hyle.Collection = (function() {
  function Collection() {}

  Collection.prototype.getAVItem = function(nameOrId) {
    var r;
    switch (typeof nameOrId) {
      case "string":
        r = this.getAVItemByName(nameOrId);
        break;
      case "number":
        r = this.getAVItemById(nameOrId);
    }
    return r;
  };

  Collection.prototype.add = function(object) {};

  Collection.prototype.find = function(key) {};

  Collection.prototype.getAVItemByName = function(name) {
    var i, j, ref;
    for (i = j = 1, ref = app.project.numItems; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      if (app.project.item(i).name === name) {
        return app.project.item(i);
      }
    }
  };

  Collection.prototype.getAVItemById = function(_id) {
    var ref;
    return (ref = this.cache.content[_id]) != null ? ref.AVItem : void 0;
  };

  Collection.prototype.getFromCache = function(_id) {
    return this.cache.content[_id];
  };

  return Collection;

})();
