// Generated by CoffeeScript 1.7.1
Hyle.Collection = (function() {
  function Collection() {}

  Collection.prototype.getAVItem = function(nameOrId) {
    var r;
    switch (typeof nameOrId) {
      case "string":
        r = this.getAVItemByName(nameOrId);
        break;
      case "number":
        r = this.getAVItemById(nameOrId);
    }
    return r;
  };

  Collection.prototype.add = function(object) {};

  Collection.prototype.find = function(key) {};

  Collection.prototype.getAVItemByName = function(name) {
    var i, _i, _ref;
    for (i = _i = 1, _ref = app.project.numItems; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      if (app.project.item(i).name === name) {
        return app.project.item(i);
      }
    }
  };

  Collection.prototype.getAVItemById = function(_id) {
    var _ref;
    return (_ref = this.cache.content[_id]) != null ? _ref.AVItem : void 0;
  };

  Collection.prototype.getFromCache = function(_id) {
    return this.cache.content[_id];
  };

  return Collection;

})();
