// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.AdjustmentLayerInstance = (function(_super) {
  __extends(AdjustmentLayerInstance, _super);

  function AdjustmentLayerInstance(data) {
    AdjustmentLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Adjustment Layer",
      adjustmentLayer: true
    });
    this.initiate(data);
    this;
  }

  return AdjustmentLayerInstance;

})(Hyle.SolidLayerInstance);
