// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.AdjustmentLayerInstance = (function(superClass) {
  extend(AdjustmentLayerInstance, superClass);

  function AdjustmentLayerInstance(data) {
    AdjustmentLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Adjustment Layer",
      adjustmentLayer: true
    });
    this.initiate(data);
    this;
  }

  return AdjustmentLayerInstance;

})(Hyle.SolidLayerInstance);
