// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.CameraLayerInstance = (function(superClass) {
  extend(CameraLayerInstance, superClass);

  function CameraLayerInstance(data) {
    CameraLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Camera",
      centerPoint: [0, 0]
    });
    this.initiate(data);
    this;
  }

  CameraLayerInstance.prototype.render = function() {
    return CameraLayerInstance.__super__.render.call(this, this.data.AVCompItemTarget.layers.addCamera(this.data.name, this.data.centerPoint));
  };

  return CameraLayerInstance;

})(Hyle.LayerInstance);
