// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FileLayerInstance = (function(superClass) {
  extend(FileLayerInstance, superClass);

  function FileLayerInstance(data) {
    this.file = {};
    FileLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      label: 5
    });
    this.initiate(data);
    this;
  }

  FileLayerInstance.prototype.render = function() {
    this.file = hyle.parser.fileItemsCollection.getFileOrImport(this.data.file);
    return FileLayerInstance.__super__.render.call(this, this.data.AVCompItemTarget.layers.add(this.file));
  };

  return FileLayerInstance;

})(Hyle.LayerInstance);
