// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.LayerInstance = (function(superClass) {
  extend(LayerInstance, superClass);

  function LayerInstance() {
    this.defaults = {};
    this.setDefaults({
      name: null,
      duration: 10
    });
  }

  LayerInstance.prototype.initiate = function(data) {
    this.sourceData = clone(data);
    this.layersCollection = hyle.parser.layersCollection;
    return this.data = this.extend(data, this.defaults);
  };

  LayerInstance.prototype.setDefaults = function(defaults) {
    var key, results;
    results = [];
    for (key in defaults) {
      results.push(this.defaults[key] = defaults[key]);
    }
    return results;
  };

  LayerInstance.prototype.setPostRenderProperties = function() {
    if (this.data.transform) {
      this.setTransform();
    }
    if (this.data.effects) {
      this.setEffects();
    }
    if (this.data.styles) {
      this.setStyles();
    }
    if (this.data.masks) {
      this.setMasks();
    }
    if (this.data.options) {
      this.setOptions();
    }
    if (this.data.parent) {
      return this.setParent();
    }
  };

  LayerInstance.prototype.setParent = function() {
    return this.layer.parent = hyle.parser.layersCollection.find(this.data.parent).layer;
  };

  LayerInstance.prototype.setTransform = function(target, data) {
    if (target == null) {
      target = null;
    }
    if (data == null) {
      data = null;
    }
    if (!target) {
      target = this.layer;
    }
    if (!data) {
      data = this.data.transform;
    }
    return this.apply(target["transform"], data, true);
  };

  LayerInstance.prototype.setOptions = function(target, data) {
    if (target == null) {
      target = null;
    }
    if (data == null) {
      data = null;
    }
    if (!target) {
      target = this.layer;
    }
    if (!data) {
      data = this.data.options;
    }
    return this.apply(target, data, true);
  };

  LayerInstance.prototype.setStyles = function() {
    var error, i, layerStyle, len, ref, results, styleData, type;
    ref = this.data.styles;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      styleData = ref[i];
      try {
        type = styleData.type.toTitleCase();
        app.executeCommand(app.findMenuCommandId(type));
        layerStyle = this.layer.property("Layer Styles").property(type);
        results.push(this.setStyleProperties(layerStyle, styleData));
      } catch (error) {
        results.push(logError("Hyle is unable find layer style named \"" + (styleData.type.toTitleCase()) + "\""));
      }
    }
    return results;
  };

  LayerInstance.prototype.setStyleProperties = function(layerStyle, styleData) {
    return this.apply(layerStyle, styleData, true);
  };

  LayerInstance.prototype.setEffects = function() {
    var effectPropertiesApplier;
    effectPropertiesApplier = new Hyle.EffectFactory(this.data.effects, this.layer);
    return effectPropertiesApplier.applyToLayer();
  };

  LayerInstance.prototype.setMasks = function() {
    var i, len, mask, maskData, ref, results;
    ref = this.data.masks;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      maskData = ref[i];
      results.push(mask = new Hyle.Mask(maskData, this.layer));
    }
    return results;
  };

  LayerInstance.prototype.render = function(layer) {
    this.layer = layer;
    this.data = this.adaptObject(this.data, {
      scope: "layer"
    });
    this.apply(this.layer, this.data);
    return this.setPostRenderProperties();
  };

  return LayerInstance;

})(Hyle.Layer);
