// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.LayersFactory = (function(superClass) {
  extend(LayersFactory, superClass);

  function LayersFactory(layersData, composition) {
    if (composition == null) {
      composition = null;
    }
    this.layersData = layersData;
    this.layersCollection = hyle.parser.layersCollection;
    this.composition = composition;
    this.createLayers();
    this;
  }

  LayersFactory.prototype.createLayers = function() {
    var i, layer, layerData, len, ref, results;
    ref = this.layersData;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      layerData = ref[i];
      if (layerData.inherit) {
        layerData = this.inherit(layerData);
      }
      layerData.AVCompItemTarget = this.getComposition(layerData);
      layer = this.createLayer(layerData);
      results.push(this.layersCollection.add(layer));
    }
    return results;
  };

  LayersFactory.prototype.createLayer = function(data) {
    var layer;
    data.type || (data.type = "Solid");
    switch (data.type.capitalize()) {
      case "Solid":
        layer = new Hyle.SolidLayerInstance(data);
        break;
      case "Adjustment":
        layer = new Hyle.AdjustmentLayerInstance(data);
        break;
      case "Null":
        layer = new Hyle.NullLayerInstance(data);
        break;
      case "Light":
        layer = new Hyle.LightLayerInstance(data);
        break;
      case "Camera":
        layer = new Hyle.CameraLayerInstance(data);
        break;
      case "Shape":
        layer = new Hyle.ShapeLayerInstance(data);
        break;
      case "Text":
        layer = new Hyle.TextLayerInstance(data);
        break;
      case "File":
        layer = new Hyle.FileLayerInstance(data);
        break;
      default:
        logError("The layer type “" + data.type + "” is unknown.");
    }
    layer.render();
    return layer;
  };

  LayersFactory.prototype.inherit = function(data) {
    var propertyName, propertyValue, ref, target;
    target = this.layersCollection.find(data.inherit);
    ref = target.sourceData;
    for (propertyName in ref) {
      propertyValue = ref[propertyName];
      if (propertyName !== "id") {
        data[propertyName] || (data[propertyName] = propertyValue);
      }
    }
    return data;
  };

  LayersFactory.prototype.getComposition = function(data) {
    var target;
    return target = (function() {
      var error;
      if (data.composition) {
        return data.composition;
      } else if (this.composition) {
        return this.composition;
      } else {
        try {
          return app.project.activeItem;
        } catch (error) {
          return alert("Layer " + this.name + " does not have a parent composition. Use the “composition” property to define one.");
        }
      }
    })();
  };

  return LayersFactory;

})(Hyle.Factory);
