// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.Layer = (function(superClass) {
  extend(Layer, superClass);

  function Layer() {
    this.defaults = {
      active: true,
      adjustmentLayer: false,
      audioActive: false,
      audioEnabled: true,
      blendingMode: 4812,
      comment: "",
      color: [0, 0, 0],
      effectsActive: true,
      elided: false,
      enabled: true,
      environmentLayer: false,
      frameBlending: false,
      frameBlendingType: 3612,
      guideLayer: false,
      hasAudio: false,
      hasTrackMatte: false,
      hasVideo: true,
      height: 1080,
      inPoint: 0,
      label: 1,
      locked: false,
      motionBlur: false,
      nullLayer: false,
      outPoint: 100,
      preserveTransparency: false,
      selected: false,
      shy: false,
      solo: false,
      startTime: 0,
      stretch: 100,
      threeDLayer: false,
      time: 0,
      timeRemapEnabled: false,
      trackMatteType: 4612,
      width: 1920
    };
  }

  return Layer;

})(Hyle.Object);
