// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.LayerInterpretor = (function(superClass) {
  extend(LayerInterpretor, superClass);

  function LayerInterpretor(layer) {
    this.layer = layer;
    this.ignoredProperties = ["nullLayer", "adjustmentLayer"];
    LayerInterpretor.__super__.constructor.apply(this, arguments);
  }

  LayerInterpretor.prototype.compact = function() {
    this.data = LayerInterpretor.__super__.compact.call(this, this.layer);
    this.interpretLayerType();
    if (this.hasEffects()) {
      this.interpretLayerEffects();
    }
    return this.data;
  };

  LayerInterpretor.prototype.interpretLayerType = function() {
    var type;
    type = "";
    if (this.layer.adjustmentLayer) {
      type = "adjustment";
    } else if (this.layer instanceof CameraLayer) {
      type = "camera";
    } else if (this.layer instanceof LightLayer) {
      type = "light";
    } else if (this.layer instanceof ShapeLayer) {
      type = "shape";
    } else if (this.layer instanceof TextLayer) {
      type = "text";
    } else if (this.layer.nullLayer) {
      type = "null";
    } else if (this.layer.source) {
      if (this.layer.source.frameDuration < 1) {
        type = "file";
      } else {
        type = "solid";
      }
    }
    return this.data.type = type;
  };

  LayerInterpretor.prototype.hasEffects = function() {
    var r;
    r = false;
    if (this.layer.Effects) {
      if (this.layer.Effects.numProperties > 0) {
        r = true;
      }
    }
    return r;
  };

  LayerInterpretor.prototype.interpretLayerEffects = function() {
    var effectInterpretor, i, j, ref, results;
    this.data.effects = [];
    results = [];
    for (i = j = 1, ref = this.layer.Effects.numProperties; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      effectInterpretor = new Hyle.EffectInterpretor(this.layer.Effects.property(i));
      results.push(this.data.effects.push(effectInterpretor.compact()));
    }
    return results;
  };

  return LayerInterpretor;

})(Hyle.Layer);
