// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.LayersCollection = (function(_super) {
  __extends(LayersCollection, _super);

  function LayersCollection() {
    this.layers = [];
  }

  LayersCollection.prototype.add = function(layer) {
    var _base;
    (_base = layer.layer)._id || (_base._id = layer.layer.name);
    return this.layers[layer.layer._id] = layer;
  };

  LayersCollection.prototype.find = function(key) {
    return this.layers[key];
  };

  return LayersCollection;

})(Object);
