// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.LightLayerInstance = (function(_super) {
  __extends(LightLayerInstance, _super);

  function LightLayerInstance(data) {
    LightLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Light",
      centerPoint: [0, 0]
    });
    this.initiate(data);
    this;
  }

  LightLayerInstance.prototype.render = function() {
    return LightLayerInstance.__super__.render.call(this, this.data.AVCompItemTarget.layers.addLight(this.data.name, this.data.centerPoint));
  };

  return LightLayerInstance;

})(Hyle.LayerInstance);
