// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.NullLayerInstance = (function(_super) {
  __extends(NullLayerInstance, _super);

  function NullLayerInstance(data) {
    NullLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Null"
    });
    this.initiate(data);
    this;
  }

  NullLayerInstance.prototype.render = function() {
    return NullLayerInstance.__super__.render.call(this, this.data.AVCompItemTarget.layers.addNull(this.data.duration));
  };

  return NullLayerInstance;

})(Hyle.LayerInstance);
