// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.SolidLayerInstance = (function(superClass) {
  extend(SolidLayerInstance, superClass);

  function SolidLayerInstance(data) {
    SolidLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Solid Layer",
      pixelAspect: 1,
      color: [0, 0, 0],
      width: 1920,
      height: 1080
    });
    this.initiate(data);
    this;
  }

  SolidLayerInstance.prototype.initiate = function(data) {
    return SolidLayerInstance.__super__.initiate.call(this, data);
  };

  SolidLayerInstance.prototype.render = function() {
    return SolidLayerInstance.__super__.render.call(this, this.data.AVCompItemTarget.layers.addSolid(this.data.color, this.data.name, this.data.width, this.data.height, this.data.pixelAspect, this.data.duration));
  };

  return SolidLayerInstance;

})(Hyle.LayerInstance);
