// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.TextLayerInstance = (function(_super) {
  __extends(TextLayerInstance, _super);

  function TextLayerInstance(data) {
    TextLayerInstance.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      name: "Text Layer",
      text: "",
      fontSize: 72,
      fillColor: [1, 1, 1],
      strokeColor: [0, 0, 0],
      strokeWidth: 0,
      font: "Helvetica",
      strokeOverFill: false,
      applyStroke: false,
      applyFill: true,
      justification: "center",
      tracking: 0
    });
    this.initiate(data);
    this;
  }

  TextLayerInstance.prototype.initiate = function(data) {
    this.hasName = data.name != null;
    return TextLayerInstance.__super__.initiate.call(this, data);
  };

  TextLayerInstance.prototype.render = function() {
    var textDocument;
    textDocument = new Hyle.TextDocument(this.data);
    TextLayerInstance.__super__.render.call(this, this.data.AVCompItemTarget.layers.addText(textDocument.getValue()));
    if (!this.hasName) {
      this.layer.name = textDocument.getValue();
    }
    textDocument.setLayer(this.layer);
    return textDocument.setTextDocument();
  };

  return TextLayerInstance;

})(Hyle.LayerInstance);
