// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.FolderItemsCollection = (function(_super) {
  __extends(FolderItemsCollection, _super);

  function FolderItemsCollection() {
    this.folders = [];
  }

  FolderItemsCollection.prototype.add = function(folder) {
    var _base;
    (_base = folder.item)._id || (_base._id = folder.item.name);
    return this.folders[folder.item._id] = folder;
  };

  FolderItemsCollection.prototype.find = function(key) {
    return this.folders[key];
  };

  return FolderItemsCollection;

})(Hyle.Collection);
