// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FolderItemsCollection = (function(superClass) {
  extend(FolderItemsCollection, superClass);

  function FolderItemsCollection() {
    this.folders = [];
  }

  FolderItemsCollection.prototype.add = function(folder) {
    var base;
    (base = folder.item)._id || (base._id = folder.item.name);
    return this.folders[folder.item._id] = folder;
  };

  FolderItemsCollection.prototype.find = function(key) {
    return this.folders[key];
  };

  return FolderItemsCollection;

})(Hyle.Collection);
