// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.FolderItemInterpretor = (function(_super) {
  __extends(FolderItemInterpretor, _super);

  function FolderItemInterpretor(folder) {
    this.folder = folder;
    this.ignoredProperties = [];
    this.ignoredValues = {
      parentFolder: "Root"
    };
    FolderItemInterpretor.__super__.constructor.apply(this, arguments);
  }

  FolderItemInterpretor.prototype.compact = function() {
    return FolderItemInterpretor.__super__.compact.call(this, this.folder);
  };

  return FolderItemInterpretor;

})(Hyle.FolderItem);
