// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FolderItemInterpretor = (function(superClass) {
  extend(FolderItemInterpretor, superClass);

  function FolderItemInterpretor(folder) {
    this.folder = folder;
    this.ignoredProperties = [];
    this.ignoredValues = {
      parentFolder: "Root"
    };
    FolderItemInterpretor.__super__.constructor.apply(this, arguments);
  }

  FolderItemInterpretor.prototype.compact = function() {
    return FolderItemInterpretor.__super__.compact.call(this, this.folder);
  };

  return FolderItemInterpretor;

})(Hyle.FolderItem);
