// Generated by CoffeeScript 1.10.0
Hyle.Api = (function() {
  function Api() {}

  Api.prototype.parse = function(data) {
    hyle.parse(data);
    return this;
  };

  Api.prototype.parseFile = function(file) {
    hyle.parse(esy.file.read(file));
    return this;
  };

  Api.prototype.compose = function() {
    return hyle.composer.compose();
  };

  Api.prototype.execute = function(fn) {
    fn();
    return this;
  };

  Api.prototype.then = function(fn) {
    this.execute(fn);
    return this;
  };

  return Api;

})();
