// Generated by CoffeeScript 1.7.1
Hyle.Debugger = (function() {
  function Debugger() {}

  Debugger.prototype.initialize = function() {
    if (hyle.debug) {
      return this.testParser();
    }
  };

  Debugger.prototype.testParser = function() {
    this.testFolders();
    this.testCompositions();
    this.testLayers();
    this.testShapes();
    this.testTexts();
    this.testMasks();
    this.testEffects();
    return this.testKeyframes();
  };

  Debugger.prototype.testComposer = function() {
    return esy.file.create("~/Dropbox/_Personnal/code/scripts/hyle/data/hyle-compose.hyle", hyle.api.compose());
  };

  Debugger.prototype.testFolders = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/folders.hyle");
  };

  Debugger.prototype.testCompositions = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/compositions.hyle");
  };

  Debugger.prototype.testLayers = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/layers.hyle");
  };

  Debugger.prototype.testShapes = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/shapeLayers.hyle");
  };

  Debugger.prototype.testTexts = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/textLayers.hyle");
  };

  Debugger.prototype.testMasks = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/masks.hyle");
  };

  Debugger.prototype.testEffects = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/effects.hyle");
  };

  Debugger.prototype.testKeyframes = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/keyframes.hyle");
  };

  Debugger.prototype.testTemp = function() {
    return hyle.api.parseFile("~/Dropbox/_Personnal/code/scripts/hyle/data/temp.hyle");
  };

  return Debugger;

})();
