// Generated by CoffeeScript 1.7.1
var Hyle;

Hyle = (function() {
  function Hyle() {}

  Hyle.prototype.initialize = function() {
    this.name = "Hyle";
    this.mail = "s.lavoie.b@gmail.com";
    this.version = "1.3.0";
    this.parser = new Hyle.Parser;
    this.composer = new Hyle.Composer;
    this["debugger"] = new Hyle.Debugger;
    this.api = new Hyle.Api;
    if (this.debug) {
      this.selfBuild("/Applications/Adobe After Effects CC 2014/Scripts/Startup");
    }
    if (this.debug) {
      this.selfBuild((new File($.fileName)).parent.parent.path);
    }
    return this["debugger"].initialize();
  };

  Hyle.prototype.selfBuild = function(path) {
    var currentPath;
    currentPath = (new File($.fileName)).parent.parent.path;
    return esy.file.buildExtendScript("" + currentPath + "/lib/hyle.js", ["" + path + "/hyle.jsx"]);
  };

  Hyle.prototype.parse = function(data) {
    app.beginUndoGroup('Hyle');
    this.parser.parse(data);
    return app.endUndoGroup();
  };

  Hyle.prototype.compose = function() {
    app.beginUndoGroup('Hyle');
    this.composer.compose();
    return app.endUndoGroup();
  };

  return Hyle;

})();
