// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.EffectFactory = (function(_super) {
  __extends(EffectFactory, _super);

  function EffectFactory(data, layer) {
    this.data = data;
    this.layer = layer;
  }

  EffectFactory.prototype.applyToLayer = function() {
    var effect, effectData, _i, _len, _ref, _results;
    _ref = this.data;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      effectData = _ref[_i];
      _results.push(effect = new Hyle.EffectInstance(effectData, this.layer));
    }
    return _results;
  };

  return EffectFactory;

})(Hyle.Factory);
