// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.EffectInterpretor = (function(_super) {
  __extends(EffectInterpretor, _super);

  function EffectInterpretor(effect) {
    this.effect = effect;
    this.ignoredProperties = ["active", "canSetEnabled", "enabled", "isEffect", "isModified", "matchName", "numProperties", "parentProperty", "propertyDepth", "propertyIndex", "propertyType"];
    this.data = {};
    EffectInterpretor.__super__.constructor.apply(this, arguments);
  }

  EffectInterpretor.prototype.compact = function() {
    this.data = EffectInterpretor.__super__.compact.call(this, this.effect, {
      bypassDefaults: true
    });
    if (this.hasEffectProperties()) {
      this.interpretEffectProperties();
    }
    return this.data;
  };

  EffectInterpretor.prototype.hasEffectProperties = function() {
    return this.effect.numProperties > 0;
  };

  EffectInterpretor.prototype.interpretEffectProperties = function() {
    var effectPropertyInterpretor, i, propertyInterpreted, _i, _ref, _results;
    this.data.properties = [];
    _results = [];
    for (i = _i = 1, _ref = this.effect.numProperties; 1 <= _ref ? _i <= _ref : _i >= _ref; i = 1 <= _ref ? ++_i : --_i) {
      effectPropertyInterpretor = new Hyle.EffectPropertyInterpretor(this.effect.property(i));
      propertyInterpreted = effectPropertyInterpretor.compact();
      if (propertyInterpreted) {
        _results.push(this.data.properties.push(propertyInterpreted));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return EffectInterpretor;

})(Hyle.Effect);
