// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.EffectFactory = (function(superClass) {
  extend(EffectFactory, superClass);

  function EffectFactory(data, layer) {
    this.data = data;
    this.layer = layer;
  }

  EffectFactory.prototype.applyToLayer = function() {
    var effect, effectData, i, len, ref, results;
    ref = this.data;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      effectData = ref[i];
      results.push(effect = new Hyle.EffectInstance(effectData, this.layer));
    }
    return results;
  };

  return EffectFactory;

})(Hyle.Factory);
