// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.EffectPropertyInterpretor = (function(superClass) {
  extend(EffectPropertyInterpretor, superClass);

  function EffectPropertyInterpretor(effectProperty) {
    this.effectProperty = effectProperty;
    this.ignoredProperties = ["active", "canSetExpression", "canVaryOverTime", "enabled", "expressionEnabled", "hasMax", "hasMin", "isTimeVarying", "isSpatial", "isModified", "matchName", "maxValue", "minValue", "numProperties", "numKeys", "parentProperty", "propertyDepth", "propertyIndex", "propertyType", "propertyValueType", "selectedKeys", "unitsText"];
    this.ignoredItems = {
      matchName: "ADBE Effect Built In Params"
    };
    this.data = {};
    EffectPropertyInterpretor.__super__.constructor.apply(this, arguments);
  }

  EffectPropertyInterpretor.prototype.compact = function() {
    if (this.effectProperty.isModified) {
      return this.data = EffectPropertyInterpretor.__super__.compact.call(this, this.effectProperty, {
        bypassDefaults: true
      });
    } else {
      return false;
    }
  };

  return EffectPropertyInterpretor;

})(Hyle.EffectProperty);
