// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.EffectPropertyGroup = (function(superClass) {
  extend(EffectPropertyGroup, superClass);

  function EffectPropertyGroup(data) {
    this.data = data;
  }

  EffectPropertyGroup.prototype.applyTo = function(object) {
    return EffectPropertyGroup.__super__.applyTo.call(this, object);
  };

  EffectPropertyGroup.prototype.adapt = function() {
    var property, propertyName, propertyValue, ref;
    ref = this.data;
    for (propertyName in ref) {
      propertyValue = ref[propertyName];
      property = new Hyle.PropertyInstance(propertyName, propertyValue);
      property.adapt({
        scope: "layer.effects"
      });
      delete this.data[propertyName];
      if (propertyName === "blending mode") {
        log((property.getPropertyName()) + " = " + (property.getPropertyValue()));
      }
      this.data[property.getPropertyName().toTitleCase()] = property.getPropertyValue();
    }
    return this;
  };

  return EffectPropertyGroup;

})(Hyle.PropertyGroup);
