// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.EffectInstance = (function(superClass) {
  extend(EffectInstance, superClass);

  function EffectInstance(data, layer) {
    this.data = data;
    this.layer = layer;
    this.effect = {};
    this.render();
  }

  EffectInstance.prototype.render = function() {
    var e, error;
    try {
      this.effect = this.layer.Effects.addProperty(this.data.type.capitalize());
    } catch (error) {
      e = error;
      alert("Hyle is unable find effect named \"" + (this.data.type.capitalize()) + "\"");
    }
    if (this.data.name) {
      this.effect.name = this.data.name;
    }
    return this.setEffectProperties();
  };

  EffectInstance.prototype.setEffectProperties = function() {
    var propertyGroup;
    propertyGroup = new Hyle.EffectPropertyGroup(this.data.properties);
    return propertyGroup.adapt().applyTo(this.effect);
  };

  return EffectInstance;

})(Hyle.Effect);
