// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.Effect = (function(superClass) {
  extend(Effect, superClass);

  function Effect() {
    this.defaults = {
      active: true,
      enabled: true,
      name: "Effect"
    };
  }

  return Effect;

})(Hyle.Object);
