// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FileItemInstance = (function(superClass) {
  extend(FileItemInstance, superClass);

  function FileItemInstance(data) {
    if (typeof data === "string") {
      data = {
        path: data
      };
    }
    FileItemInstance.__super__.constructor.apply(this, arguments);
    this.initiate(data);
  }

  FileItemInstance.prototype.store = function() {
    var importOptions;
    importOptions = new ImportOptions(File(this.data.path));
    if (this.data.sequence) {
      importOptions.sequence = true;
    }
    FileItemInstance.__super__.store.call(this, app.project.importFile(importOptions));
    if (!this.data.selected) {
      return this.item.selected = false;
    }
  };

  FileItemInstance.prototype.getFileName = function() {
    return esy.file.fileName(this.item.path);
  };

  return FileItemInstance;

})(Hyle.FileItem);
