// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FileItemsFactory = (function(superClass) {
  extend(FileItemsFactory, superClass);

  function FileItemsFactory(filesData) {
    this.files = [];
    this.fileItemsCollection = hyle.parser.fileItemsCollection;
    this.createFiles(filesData);
    this;
  }

  FileItemsFactory.prototype.createFiles = function(filesData) {
    var fileData, i, len, results;
    results = [];
    for (i = 0, len = filesData.length; i < len; i++) {
      fileData = filesData[i];
      results.push(this.createFile(fileData));
    }
    return results;
  };

  FileItemsFactory.prototype.createFile = function(fileData) {
    var file;
    file = new Hyle.FileItemInstance(fileData);
    file.store();
    return this.fileItemsCollection.add(file);
  };

  return FileItemsFactory;

})(Hyle.Factory);
