// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.FileItem = (function(_super) {
  __extends(FileItem, _super);

  function FileItem(data) {
    FileItem.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      label: 5,
      path: ""
    });
    this;
  }

  return FileItem;

})(Hyle.Item);
