// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Hyle.FileItemsFactory = (function(_super) {
  __extends(FileItemsFactory, _super);

  function FileItemsFactory(filesData) {
    this.files = [];
    this.fileItemsCollection = hyle.parser.fileItemsCollection;
    this.createFiles(filesData);
    this;
  }

  FileItemsFactory.prototype.createFiles = function(filesData) {
    var fileData, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = filesData.length; _i < _len; _i++) {
      fileData = filesData[_i];
      _results.push(this.createFile(fileData));
    }
    return _results;
  };

  FileItemsFactory.prototype.createFile = function(fileData) {
    var file;
    file = new Hyle.FileItemInstance(fileData);
    file.store();
    return this.fileItemsCollection.add(file);
  };

  return FileItemsFactory;

})(Hyle.Factory);
