// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FileItemInterpretor = (function(superClass) {
  extend(FileItemInterpretor, superClass);

  function FileItemInterpretor(file) {
    this.file = file;
    this.ignoredProperties = ["items", "numItems", "typeName"];
    FileItemInterpretor.__super__.constructor.apply(this, arguments);
  }

  FileItemInterpretor.prototype.compact = function() {
    var data;
    data = {};
    if (this.file.parentFolder.name !== "Solids") {
      data = FileItemInterpretor.__super__.compact.call(this, this.file);
      data.path = this.file.mainSource.file.toString();
    }
    return data;
  };

  return FileItemInterpretor;

})(Hyle.FileItem);
