// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Hyle.FileItem = (function(superClass) {
  extend(FileItem, superClass);

  function FileItem(data) {
    FileItem.__super__.constructor.apply(this, arguments);
    this.setDefaults({
      label: 5,
      path: ""
    });
    this;
  }

  return FileItem;

})(Hyle.Item);
